dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk11

git:
  depth: 1 #clone repository to a maximum depth of 1 commits

script: "mvn clean install -Dmaven.javadoc.skip=true -B -V"

after_success:
  - mvn clean integration-test