CREATE SEQUENCE SEQ_DRIVER;

CREATE TABLE TB_DRIVER(
    DRIVERID NUMERIC(20),
    DRIVERREF VARCHAR(100) NOT NULL,
    NUMBER NUMERIC(20),
    CODE VARCHAR(3),
    FORENAME VARCHAR(50) NOT NULL,
    SURNAME VARCHAR(50) NOT NULL,
    DOB DATE NOT NULL,
    NATIONALITY VARCHAR(50) NOT NULL,
    URL VARCHAR(255) NOT NULL,
    CONSTRAINT PK_DRIVER PRIMARY KEY (DRIVERID)
);