CREATE SEQUENCE SEQ_QUALIFYING;

CREATE TABLE TB_QUALIFYING(
    QUALIFYINGID NUMERIC(20),
    RACEID NUMERIC(20) NOT NULL,
    DRIVERID NUMERIC(20) NOT NULL,
    CONSTRUCTORID NUMERIC(20) NOT NULL,
    NUMBER NUMERIC(20) NOT NULL,
    POSITION NUMERIC(20) NOT NULL,
    Q1 TIME,
    Q2 TIME,
    Q3 TIME,
    CONSTRAINT PK_QUALIFYING PRIMARY KEY (QUALIFYINGID),
    CONSTRAINT FK_QUALIFYING_RACE FOREIGN KEY (RACEID) REFERENCES TB_RACE (RACEID),
    CONSTRAINT FK_QUALIFYING_DRIVER FOREIGN KEY (DRIVERID) REFERENCES TB_DRIVER (DRIVERID),
    CONSTRAINT FK_QUALIFYING_CONSTRUCTOR FOREIGN KEY (CONSTRUCTORID) REFERENCES TB_CONSTRUCTOR (CONSTRUCTORID)
);

