CREATE SEQUENCE SEQ_QUALIFYING;

CREATE TABLE TB_QUALIFYING(
    QUALIFYINGID NUMERIC(20),
    RACE NUMERIC(20) NOT NULL,
    DRIVER NUMERIC(20) NOT NULL,
    CONSTRUCTOR NUMERIC(20) NOT NULL,
    NUMBER NUMERIC(20) NOT NULL,
    POSITION NUMERIC(20) NOT NULL,
    Q1 TIME,
    Q2 TIME,
    Q3 TIME,
    CONSTRAINT PK_QUALIFYING PRIMARY KEY (QUALIFYINGID),
    CONSTRAINT FK_QUALIFYING_RACE FOREIGN KEY (RACE) REFERENCES TB_RACE (RACEID),
    CONSTRAINT FK_QUALIFYING_DRIVER FOREIGN KEY (DRIVER) REFERENCES TB_DRIVER (DRIVERID),
    CONSTRAINT FK_QUALIFYING_CONSTRUCTOR FOREIGN KEY (CONSTRUCTOR) REFERENCES TB_CONSTRUCTOR (CONSTRUCTORID)
);

