CREATE SEQUENCE SEQ_LAPTIMES;

CREATE TABLE TB_LAPTIMES(
    LAPTIMESID NUMERIC(20),
    RACEID NUMERIC(20) NOT NULL,
    DRIVERID NUMERIC(20) NOT NULL,
    LAP NUMERIC(20) NOT NULL,
    POSITION NUMERIC(20) NOT NULL,
    TIME TIME,
    MILLISECONDS NUMERIC(20) NOT NULL,
    CONSTRAINT PK_LAPTIMES PRIMARY KEY (LAPTIMESID),
    CONSTRAINT FK_LAPTIMES_RACE FOREIGN KEY (RACEID) REFERENCES TB_RACE (RACEID),
    CONSTRAINT FK_LAPTIMES_DRIVER FOREIGN KEY (DRIVERID) REFERENCES TB_DRIVER (DRIVERID)
);


