CREATE SEQUENCE SEQ_PITSTOP;

CREATE TABLE TB_PITSTOP(
    PITSTOPID NUMERIC(20),
    RACEID NUMERIC(20) NOT NULL,
    DRIVERID NUMERIC(20) NOT NULL,
    STOP NUMERIC(3) NOT NULL,
    LAP NUMERIC(3) NOT NULL,
    TIME VARCHAR(10) NOT NULL,
    DURATION TIME NOT NULL,
    MILLISECONDS NUMERIC(20) NOT NULL,
    CONSTRAINT PK_PISTOP PRIMARY KEY (PITSTOPID),
    CONSTRAINT FK_PITSTOP_RACE FOREIGN KEY (RACEID) REFERENCES TB_RACE (RACEID),
    CONSTRAINT FK_PITSTOP_DRIVER FOREIGN KEY (DRIVERID) REFERENCES TB_DRIVER (DRIVERID)
);