CREATE SEQUENCE SEQ_CONSTRUCTORRESULT;

CREATE TABLE TB_CONSTRUCTORRESULT(
    CONSTRUCTORRESULTID NUMERIC(20),
    RACEID NUMERIC(20) NOT NULL,
    CONSTRUCTORID NUMERIC(20) NOT NULL,
    POINTS NUMERIC(20) NOT NULL,
    STATUS NUMERIC(20),
    CONSTRAINT PK_CONSTRUCTORRESULT PRIMARY KEY (CONSTRUCTORRESULTID),
    CONSTRAINT FK_CONSTRUCTORRESULT_RACE FOREIGN KEY (RACEID) REFERENCES TB_RACE (RACEID),
    CONSTRAINT FK_CONSTRUCTORRESULT_CONSTRUCTOR FOREIGN KEY (CONSTRUCTORID) REFERENCES TB_CONSTRUCTOR (CONSTRUCTORID)
);