CREATE SEQUENCE SEQ_SPRINTRESULT;

CREATE TABLE TB_SPRINTRESULT(
    SPRINTRESULTID NUMERIC(20),
    RESULTID NUMERIC(20) NOT NULL,
    RACEID NUMERIC(20) NOT NULL,
    DRIVERID NUMERIC(20) NOT NULL,
    CONSTRUCTORID NUMERIC(20) NOT NULL,
    NUMBER NUMERIC(20) NOT NULL,
    GRID NUMERIC(20) NOT NULL,
    POSITION NUMERIC(20),
    POSITIONTEXT VARCHAR(50) NOT NULL,
    POSITIONORDER NUMERIC(20) NOT NULL,
    POINTS NUMERIC(20) NOT NULL,
    LAPS NUMERIC(20) NOT NULL,
    TIME VARCHAR(20),
    MILLISECONDS NUMERIC(20),
    FASTESTLAP NUMERIC(20),
    FASTESTLAPTIME TIME,
    STATUSID NUMERIC(20),
    CONSTRAINT PK_SPRINTRESULT PRIMARY KEY (SPRINTRESULTID),
    CONSTRAINT PK_SPRINTRESULT_RESULT FOREIGN KEY (RESULTID) REFERENCES TB_RESULT (RESULTID),
    CONSTRAINT PK_SPRINTRESULT_RACE FOREIGN KEY (RACEID) REFERENCES TB_RACE (RACEID),
    CONSTRAINT PK_SPRINTRESULT_DRIVER FOREIGN KEY (DRIVERID) REFERENCES TB_DRIVER (DRIVERID),
    CONSTRAINT PK_SPRINTRESULT_CONSTRUCTOR FOREIGN KEY (CONSTRUCTORID) REFERENCES TB_CONSTRUCTOR (CONSTRUCTORID),
    CONSTRAINT PK_SPRINTRESULT_STATUS FOREIGN KEY (STATUSID) REFERENCES TB_STATUS (STATUSID)
);