CREATE SEQUENCE SEQ_DRIVERSTANDING;

CREATE TABLE TB_DRIVERSTANDING(
    DRIVERSTANDINGID NUMERIC(20),
    RACEID NUMERIC(20) NOT NULL,
    DRIVERID NUMERIC(20) NOT NULL,
    POINTS NUMERIC(20) NOT NULL,
    POSITION NUMERIC(20) NOT NULL,
    POSITIONTEXT VARCHAR(20),
    WINS NUMERIC(20),
    CONSTRAINT PK_DRIVERSTANDINGID PRIMARY KEY (DRIVERSTANDINGID),
    CONSTRAINT FK_DRIVERSTANDING_RACE FOREIGN KEY (RACEID) REFERENCES TB_RACE (RACEID),
    CONSTRAINT FK_DRIVERSTANDING_DRIVER FOREIGN KEY (DRIVERID) REFERENCES TB_DRIVER (DRIVERID)
);