INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Finished');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Disqualified');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Accident');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Collision');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Engine');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Gearbox');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Transmission');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Clutch');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Hydraulics');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Electrical');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+1 Lap');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+2 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+3 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+4 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+5 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+6 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+7 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+8 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+9 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Spun off');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Radiator');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Suspension');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Brakes');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Differential');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Overheating');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Mechanical');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Tyre');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Driver Seat');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Puncture');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Driveshaft');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Retired');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Fuel pressure');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Front wing');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Water pressure');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Refuelling');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Wheel');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Throttle');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Steering');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Technical');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Electronics');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Broken wing');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Heat shield fire');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Exhaust');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Oil leak');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+11 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Wheel rim');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Water leak');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Fuel pump');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Track rod');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'+17 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_status'),'Oil pressure');
CREATE SEQUENCE seq_serial START 53;
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial'),'+13 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial'),'Withdrew');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial'),'+12 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial'),'Engine fire');
CREATE SEQUENCE seq_serial2 START 58;
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+26 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Tyre puncture');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Out of fuel');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Wheel nut');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Not classified');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Pneumatics');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Handling');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Rear wing');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Fire');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Wheel bearing');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Physical');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Fuel system');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Oil line');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Fuel rig');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Launch control');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Injured');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Fuel');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Power loss');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Vibrations');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'107% Rule');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Safety');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Drivetrain');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Ignition');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Did not qualify');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Injury');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Chassis');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Battery');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Stalled');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Halfshaft');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Crankshaft');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+10 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Safety concerns');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Not restarted');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Alternator');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Underweight');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Safety belt');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Oil pump');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Fuel leak');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Excluded');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Did not prequalify');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Injection');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Distributor');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Driver unwell');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Turbo');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'CV joint');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Water pump');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Fatal accident');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Spark plugs');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Fuel pipe');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Eye injury');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Oil pipe');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Axle');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Water pipe');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+14 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+15 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+25 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+18 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+22 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+16 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+24 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+29 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+23 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+21 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Magneto');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+44 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+30 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+19 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+46 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Supercharger');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+20 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+42 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Engine misfire');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Collision damage');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Power Unit');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'ERS');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+49 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'+38 Laps');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Brake duct');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Seat');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Damage');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Debris');
INSERT INTO public.tb_status(statusid,status) VALUES (nextval('seq_serial2'),'Illness');
DROP SEQUENCE seq_serial;
DROP SEQUENCE seq_serial2;