INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Finished');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Disqualified');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Accident');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Collision');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Engine');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Gearbox');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Transmission');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Clutch');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Hydraulics');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Electrical');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+1 Lap');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+2 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+3 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+4 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+5 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+6 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+7 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+8 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+9 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Spun off');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Radiator');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Suspension');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Brakes');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Differential');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Overheating');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Mechanical');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Tyre');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Driver Seat');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Puncture');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Driveshaft');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Retired');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Fuel pressure');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Front wing');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Water pressure');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Refuelling');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Wheel');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Throttle');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Steering');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Technical');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Electronics');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Broken wing');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Heat shield fire');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Exhaust');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Oil leak');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+11 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Wheel rim');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Water leak');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Fuel pump');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Track rod');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+17 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Oil pressure');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+42 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+13 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Withdrew');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+12 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Engine fire');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Engine misfire');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+26 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Tyre puncture');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Out of fuel');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Wheel nut');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Not classified');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Pneumatics');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Handling');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Rear wing');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Fire');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Wheel bearing');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Physical');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Fuel system');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Oil line');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Fuel rig');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Launch control');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Injured');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Fuel');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Power loss');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Vibrations');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '107% Rule');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Safety');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Drivetrain');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Ignition');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Did not qualify');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Injury');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Chassis');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Battery');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Stalled');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Halfshaft');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Crankshaft');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+10 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Safety concerns');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Not restarted');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Alternator');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Underweight');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Safety belt');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Oil pump');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Fuel leak');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Excluded');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Did not prequalify');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Injection');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Distributor');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Driver unwell');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Turbo');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'CV joint');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Water pump');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Fatal accident');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Spark plugs');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Fuel pipe');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Eye injury');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Oil pipe');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Axle');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Water pipe');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+14 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+15 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+25 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+18 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+22 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+16 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+24 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+29 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+23 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+21 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Magneto');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+44 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+30 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+19 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+46 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Supercharger');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+20 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Collision damage');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Power Unit');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'ERS');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+49 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), '+38 Laps');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Brake duct');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Seat');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Damage');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Debris');
INSERT INTO public.tb_status (statusid, status) VALUES (nextval('seq_status'), 'Illness');