CREATE SEQUENCE SEQ_CONSTRUCTOR;

CREATE TABLE TB_CONSTRUCTOR(
    CONSTRUCTORID NUMERIC(20),
    CONSTRUCTORREF VARCHAR(100)  NOT NULL,
    NAME VARCHAR(100)  NOT NULL,
    NATIONALITY VARCHAR(100)  NOT NULL,
    URL VARCHAR(255)  NOT NULL,
    CONSTRAINT PK_CONSTRUCTOR PRIMARY KEY (CONSTRUCTORID)
);