INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'mclaren','McLaren','British','http://en.wikipedia.org/wiki/McLaren');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'bmw_sauber','BMW Sauber','German','http://en.wikipedia.org/wiki/BMW_Sauber');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'williams','Williams','British','http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'renault','Renault','French','http://en.wikipedia.org/wiki/Renault_in_Formula_One');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'toro_rosso','Toro Rosso','Italian','http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'ferrari','Ferrari','Italian','http://en.wikipedia.org/wiki/Scuderia_Ferrari');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'toyota','Toyota','Japanese','http://en.wikipedia.org/wiki/Toyota_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'super_aguri','Super Aguri','Japanese','http://en.wikipedia.org/wiki/Super_Aguri_F1');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'red_bull','Red Bull','Austrian','http://en.wikipedia.org/wiki/Red_Bull_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'force_india','Force India','Indian','http://en.wikipedia.org/wiki/Racing_Point_Force_India');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'honda','Honda','Japanese','http://en.wikipedia.org/wiki/Honda_Racing_F1');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'spyker','Spyker','Dutch','http://en.wikipedia.org/wiki/Spyker_F1');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'mf11','MF1','Russian','http://en.wikipedia.org/wiki/Midland_F1_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'spyker_mf1','Spyker MF1','Dutch','http://en.wikipedia.org/wiki/Midland_F1_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'sauber','Sauber','Swiss','http://en.wikipedia.org/wiki/Sauber');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'bar','BAR','British','http://en.wikipedia.org/wiki/British_American_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'jordan','Jordan','Irish','http://en.wikipedia.org/wiki/Jordan_Grand_Prix');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'minardi','Minardi','Italian','http://en.wikipedia.org/wiki/Minardi');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'jaguar','Jaguar','British','http://en.wikipedia.org/wiki/Jaguar_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'prost','Prost','French','http://en.wikipedia.org/wiki/Prost_Grand_Prix');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'arrows','Arrows','British','http://en.wikipedia.org/wiki/Arrows_Grand_Prix_International');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'benetton','Benetton','Italian','http://en.wikipedia.org/wiki/Benetton_Formula');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'brawn','Brawn','British','http://en.wikipedia.org/wiki/Brawn_GP');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'stewart','Stewart','British','http://en.wikipedia.org/wiki/Stewart_Grand_Prix');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'tyrrell','Tyrrell','British','http://en.wikipedia.org/wiki/Tyrrell_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'lola','Lola','British','http://en.wikipedia.org/wiki/MasterCard_Lola');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'ligier','Ligier','French','http://en.wikipedia.org/wiki/Ligier');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'forti','Forti','Italian','http://en.wikipedia.org/wiki/Forti');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'footwork','Footwork','British','http://en.wikipedia.org/wiki/Footwork_Arrows');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'pacific','Pacific','British','http://en.wikipedia.org/wiki/Pacific_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'simtek','Simtek','British','http://en.wikipedia.org/wiki/Simtek');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'team_lotus','Team Lotus','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'larrousse','Larrousse','French','http://en.wikipedia.org/wiki/Larrousse');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'brabham','Brabham','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'dallara','Dallara','Italian','http://en.wikipedia.org/wiki/Dallara');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'fondmetal','Fondmetal','Italian','http://en.wikipedia.org/wiki/Fondmetal');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'march','March','British','http://en.wikipedia.org/wiki/March_Engineering');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'moda','Andrea Moda','Italian','http://en.wikipedia.org/wiki/Andrea_Moda_Formula');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'ags','AGS','French','http://en.wikipedia.org/wiki/Automobiles_Gonfaronnaises_Sportives');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'lambo','Lambo','Italian','http://en.wikipedia.org/wiki/Modena_(racing_team)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'leyton','Leyton House','British','http://en.wikipedia.org/wiki/Leyton_House');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_constructor'),'coloni','Coloni','Italian','http://en.wikipedia.org/wiki/Enzo_Coloni_Racing_Car_Systems');
CREATE SEQUENCE seq_serial START 44;
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'eurobrun','Euro Brun','Italian','http://en.wikipedia.org/wiki/Euro_Brun');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'osella','Osella','Italian','http://en.wikipedia.org/wiki/Osella');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'onyx','Onyx','British','http://en.wikipedia.org/wiki/Onyx_(racing_team)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'life','Life','Italian','http://en.wikipedia.org/wiki/Life_(Racing_Team)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'rial','Rial','German','http://en.wikipedia.org/wiki/Rial_%28racing_team%29');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'zakspeed','Zakspeed','German','http://en.wikipedia.org/wiki/Zakspeed');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'ram','RAM','British','http://en.wikipedia.org/wiki/RAM_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'alfa','Alfa Romeo','Swiss','http://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'spirit','Spirit','British','http://en.wikipedia.org/wiki/Spirit_(racing_team)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'toleman','Toleman','British','http://en.wikipedia.org/wiki/Toleman');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'ats','ATS','Italian','http://en.wikipedia.org/wiki/ATS_(wheels)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'theodore','Theodore','Hong Kong','http://en.wikipedia.org/wiki/Theodore_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'fittipaldi','Fittipaldi','Brazilian','http://en.wikipedia.org/wiki/Fittipaldi_%28constructor%29');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'ensign','Ensign','British','http://en.wikipedia.org/wiki/Ensign_%28racing_team%29');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'shadow','Shadow','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'wolf','Wolf','Canadian','http://en.wikipedia.org/wiki/Walter_Wolf_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'merzario','Merzario','Italian','http://en.wikipedia.org/wiki/Merzario');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'kauhsen','Kauhsen','German','http://en.wikipedia.org/wiki/Kauhsen');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'rebaque','Rebaque','Mexican','http://en.wikipedia.org/wiki/Rebaque');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'surtees','Surtees','British','http://en.wikipedia.org/wiki/Surtees');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'hesketh','Hesketh','British','http://en.wikipedia.org/wiki/Hesketh_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'martini','Martini','French','http://en.wikipedia.org/wiki/Martini_(cars)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'brm','BRM','British','http://en.wikipedia.org/wiki/BRM');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'penske','Penske','American','http://en.wikipedia.org/wiki/Penske_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'lec','LEC','British','http://en.wikipedia.org/wiki/LEC_(Formula_One)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'mcguire','McGuire','Australian','http://en.wikipedia.org/wiki/McGuire_(Formula_One)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'boro','Boro','Dutch','http://en.wikipedia.org/wiki/Boro_(Formula_One)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'apollon','Apollon','Swiss','http://en.wikipedia.org/wiki/Apollon_(Formula_One)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'kojima','Kojima','Japanese','http://en.wikipedia.org/wiki/Kojima_Engineering');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'parnelli','Parnelli','American','http://en.wikipedia.org/wiki/Parnelli');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'maki','Maki','Japanese','http://en.wikipedia.org/wiki/Maki_(cars)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'hill','Embassy Hill','British','http://en.wikipedia.org/wiki/Hill_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'lyncar','Lyncar','British','http://en.wikipedia.org/wiki/Lyncar');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'trojan','Trojan','British','http://en.wikipedia.org/wiki/Trojan_(Racing_team)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'amon','Amon','New Zealander','http://en.wikipedia.org/wiki/Amon_(Formula_One_team)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'token','Token','British','http://en.wikipedia.org/wiki/Token_(Racing_team)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'iso_marlboro','Iso Marlboro','British','http://en.wikipedia.org/wiki/Iso_Marlboro');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'tecno','Tecno','Italian','http://en.wikipedia.org/wiki/Tecno');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'matra','Matra','French','http://en.wikipedia.org/wiki/Matra');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'politoys','Politoys','British','http://en.wikipedia.org/wiki/Frank_Williams_Racing_Cars');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'connew','Connew','British','http://en.wikipedia.org/wiki/Connew');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'bellasi','Bellasi','Swiss','http://en.wikipedia.org/wiki/Bellasi');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'tomaso','De Tomaso','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'cooper','Cooper','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'eagle','Eagle','American','http://en.wikipedia.org/wiki/Anglo_American_Racers');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'lds','LDS','South African','http://en.wikipedia.org/wiki/LDS_(automobile)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'protos','Protos','British','http://en.wikipedia.org/wiki/Protos_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'shannon','Shannon','British','http://en.wikipedia.org/wiki/Shannon_(Formula_One)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'scirocco','Scirocco','British','http://en.wikipedia.org/wiki/Scirocco-Powell');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'re','RE','Rhodesian','http://en.wikipedia.org/wiki/RE_%28automobile%29');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'brp','BRP','British','http://en.wikipedia.org/wiki/British_Racing_Partnership');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'porsche','Porsche','German','http://en.wikipedia.org/wiki/Porsche_in_Formula_One');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'derrington','Derrington','British','http://en.wikipedia.org/wiki/Derrington-Francis');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'gilby','Gilby','British','http://en.wikipedia.org/wiki/Gilby');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'stebro','Stebro','Canadian','http://en.wikipedia.org/wiki/Stebro');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'emeryson','Emeryson','British','http://en.wikipedia.org/wiki/Emeryson');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'enb','ENB','Belgian','http://en.wikipedia.org/wiki/Ecurie_Nationale_Belge');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'jbw','JBW','British','http://en.wikipedia.org/wiki/JBW');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'ferguson','Ferguson','British','http://en.wikipedia.org/wiki/Ferguson_Research_Ltd.');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'mbm','MBM','Swiss','http://en.wikipedia.org/wiki/Monteverdi_Basel_Motors');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'behra-porsche','Behra-Porsche','Italian','http://en.wikipedia.org/wiki/Behra-Porsche');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'maserati','Maserati','Italian','http://en.wikipedia.org/wiki/Maserati');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'scarab','Scarab','American','http://en.wikipedia.org/wiki/Scarab_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'watson','Watson','American','http://en.wikipedia.org/wiki/A.J._Watson');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'epperly','Epperly','American','http://en.wikipedia.org/wiki/Epperly');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'phillips','Phillips','American','http://en.wikipedia.org/wiki/Phillips_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'lesovsky','Lesovsky','American','http://en.wikipedia.org/wiki/Lesovsky');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'trevis','Trevis','American','http://en.wikipedia.org/wiki/Trevis');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'meskowski','Meskowski','American','http://en.wikipedia.org/wiki/Meskowski');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'kurtis_kraft','Kurtis Kraft','American','http://en.wikipedia.org/wiki/Kurtis_Kraft');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'kuzma','Kuzma','American','http://en.wikipedia.org/wiki/Kuzma_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'vhristensen','Christensen','American','http://en.wikipedia.org/wiki/Christensen_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'ewing','Ewing','American','http://en.wikipedia.org/wiki/Ewing_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'aston_martin','Aston Martin','British','http://en.wikipedia.org/wiki/Aston_Martin_in_Formula_One');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'vanwall','Vanwall','British','http://en.wikipedia.org/wiki/Vanwall');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'moore','Moore','American','http://en.wikipedia.org/wiki/Moore_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'dunn','Dunn','American','http://en.wikipedia.org/wiki/Dunn_Engineering');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'elder','Elder','American','http://en.wikipedia.org/wiki/Elder_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'sutton','Sutton','American','http://en.wikipedia.org/wiki/Sutton_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'fry','Fry','British','http://en.wikipedia.org/wiki/Fry_(racing_team)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'tec-mec','Tec-Mec','Italian','http://en.wikipedia.org/wiki/Tec-Mec');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'connaught','Connaught','British','http://en.wikipedia.org/wiki/Connaught_Engineering');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'alta','Alta','British','http://en.wikipedia.org/wiki/Alta_auto_racing_team');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'osca','OSCA','Italian','http://en.wikipedia.org/wiki/Officine_Specializate_Costruzione_Automobili');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'gordini','Gordini','French','http://en.wikipedia.org/wiki/Gordini');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'stevens','Stevens','American','http://en.wikipedia.org/wiki/Stevens_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'bugatti','Bugatti','French','http://en.wikipedia.org/wiki/Bugatti');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'mercedes','Mercedes','German','http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'lancia','Lancia','Italian','http://en.wikipedia.org/wiki/Lancia_in_Formula_One');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'hwm','HWM','British','http://en.wikipedia.org/wiki/Hersham_and_Walton_Motors');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'schroeder','Schroeder','American','http://en.wikipedia.org/wiki/Schroeder_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'pawl','Pawl','American','http://en.wikipedia.org/wiki/Pawl_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'pankratz','Pankratz','American','http://en.wikipedia.org/wiki/Pankratz');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'arzani-volpini','Arzani-Volpini','Italian','http://en.wikipedia.org/wiki/Arzani-Volpini');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'nichels','Nichels','American','http://en.wikipedia.org/wiki/Nichels');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'bromme','Bromme','American','http://en.wikipedia.org/wiki/Bromme');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'klenk','Klenk','German','http://en.wikipedia.org/wiki/Klenk');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'simca','Simca','French','http://en.wikipedia.org/wiki/Simca');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'turner','Turner','American','http://en.wikipedia.org/wiki/Turner_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'del_roy','Del Roy','American','http://en.wikipedia.org/wiki/Del_Roy');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'veritas','Veritas','German','http://en.wikipedia.org/wiki/Veritas_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'bmw','BMW','German','http://en.wikipedia.org/wiki/BMW');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'emw','EMW','East German','http://en.wikipedia.org/wiki/Eisenacher_Motorenwerk');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'afm','AFM','German','http://en.wikipedia.org/wiki/Alex_von_Falkenhausen_Motorenbau');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'frazer_nash','Frazer Nash','British','http://en.wikipedia.org/wiki/Frazer_Nash');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'sherman','Sherman','American','http://en.wikipedia.org/wiki/Sherman_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'deidt','Deidt','American','http://en.wikipedia.org/wiki/Deidt');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'era','ERA','British','http://en.wikipedia.org/wiki/English_Racing_Automobiles');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'butterworth','Aston Butterworth','British','http://en.wikipedia.org/wiki/Aston_Butterworth');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'cisitalia','Cisitalia','Italian','http://en.wikipedia.org/wiki/Cisitalia');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'lago','Talbot-Lago','French','http://en.wikipedia.org/wiki/Talbot-Lago');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'hall','Hall','American','http://en.wikipedia.org/wiki/Hall_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'marchese','Marchese','American','http://en.wikipedia.org/wiki/Marchese_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'langley','Langley','American','http://en.wikipedia.org/wiki/Langley_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'rae','Rae','American','http://en.wikipedia.org/wiki/Rae_(motorsport)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'olson','Olson','American','http://en.wikipedia.org/wiki/Olson_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'wetteroth','Wetteroth','American','http://en.wikipedia.org/wiki/Wetteroth');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'adams','Adams','American','http://en.wikipedia.org/wiki/Adams_(constructor)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'snowberger','Snowberger','American','http://en.wikipedia.org/wiki/Snowberger');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'milano','Milano','Italian','http://en.wikipedia.org/wiki/Scuderia_Milano');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial'),'hrt','HRT','Spanish','http://en.wikipedia.org/wiki/Hispania_Racing');
CREATE SEQUENCE seq_serial2 START 166;
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'virgin','Virgin','British','http://en.wikipedia.org/wiki/Virgin_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'cooper-maserati','Cooper-Maserati','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'cooper-osca','Cooper-OSCA','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'cooper-borgward','Cooper-Borgward','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'cooper-climax','Cooper-Climax','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'cooper-castellotti','Cooper-Castellotti','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'lotus-climax','Lotus-Climax','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'lotus-maserati','Lotus-Maserati','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'de_tomaso-osca','De Tomaso-Osca','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'de_tomaso-alfa_romeo','De Tomaso-Alfa Romeo','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'lotus-brm','Lotus-BRM','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'lotus-borgward','Lotus-Borgward','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'cooper-alfa_romeo','Cooper-Alfa Romeo','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'de_tomaso-ferrari','De Tomaso-Ferrari','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'lotus-ford','Lotus-Ford','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'brabham-brm','Brabham-BRM','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'brabham-ford','Brabham-Ford','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'brabham-climax','Brabham-Climax','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'lds-climax','LDS-Climax','South African','http://en.wikipedia.org/wiki/LDS_(automobile)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'lds-alfa_romeo','LDS-Alfa Romeo','South African','http://en.wikipedia.org/wiki/LDS_(automobile)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'cooper-ford','Cooper-Ford','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'mclaren-ford','McLaren-Ford','British','http://en.wikipedia.org/wiki/Team_McLaren');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'mclaren-seren','McLaren-Serenissima','British','http://en.wikipedia.org/wiki/Team_McLaren');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'eagle-climax','Eagle-Climax','American','http://en.wikipedia.org/wiki/Anglo_American_Racers');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'eagle-weslake','Eagle-Weslake','American','http://en.wikipedia.org/wiki/Anglo_American_Racers');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'brabham-repco','Brabham-Repco','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'cooper-ferrari','Cooper-Ferrari','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'cooper-ats','Cooper-ATS','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'mclaren-brm','McLaren-BRM','British','http://en.wikipedia.org/wiki/McLaren_(racing)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'cooper-brm','Cooper-BRM','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'matra-ford','Matra-Ford','French','http://en.wikipedia.org/wiki/Matra');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'brm-ford','BRM-Ford','British','http://en.wikipedia.org/wiki/BRM');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'mclaren-alfa_romeo','McLaren-Alfa Romeo','British','http://en.wikipedia.org/wiki/McLaren_(racing)');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'march-alfa_romeo','March-Alfa Romeo','British','http://en.wikipedia.org/wiki/March_Engineering');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'march-ford','March-Ford','British','http://en.wikipedia.org/wiki/March_Engineering');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'lotus-pw','Lotus-Pratt &amp; Whitney','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'shadow-ford','Shadow-Ford','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'shadow-matra','Shadow-Matra','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'brabham-alfa_romeo','Brabham-Alfa Romeo','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'lotus_racing','Lotus','Malaysian','http://en.wikipedia.org/wiki/Lotus_Racing');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'marussia','Marussia','Russian','http://en.wikipedia.org/wiki/Marussia_F1');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'caterham','Caterham','Malaysian','http://en.wikipedia.org/wiki/Caterham_F1');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'lotus_f1','Lotus F1','British','http://en.wikipedia.org/wiki/Lotus_F1');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'manor','Manor Marussia','British','http://en.wikipedia.org/wiki/Manor_Motorsport');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'haas','Haas F1 Team','American','http://en.wikipedia.org/wiki/Haas_F1_Team');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial2'),'racing_point','Racing Point','British','http://en.wikipedia.org/wiki/Racing_Point_F1_Team');
CREATE SEQUENCE seq_serial3 START 213;
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial3'),'alphatauri','AlphaTauri','Italian','http://en.wikipedia.org/wiki/Scuderia_AlphaTauri');
INSERT INTO public.tb_constructor(constructorid,constructorref,name,nationality,url) VALUES (nextval('seq_serial3'),'alpine','Alpine F1 Team','French','http://en.wikipedia.org/wiki/Alpine_F1_Team:');
DROP SEQUENCE seq_serial;
DROP SEQUENCE seq_serial2;
DROP SEQUENCE seq_serial3;