CREATE SEQUENCE SEQ_PRODUCT;

CREATE TABLE TB_PRODUCT(
    PRODUCTID NUMERIC(20),
    NAME VARCHAR(200) NOT NULL,
    PRICE DECIMAL(20,2) NOT NULL,
    QUANTITY NUMERIC(20) NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCTID)
);