CREATE SEQUENCE SEQ_CIRCUIT;

CREATE TABLE TB_CIRCUIT(
    CIRCUITID NUMERIC(20),
    CIRCUITREF VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    LAT NUMERIC(10,2) NOT NULL,
    LNG NUMERIC(10,2) NOT NULL,
    ALT NUMERIC(20),
    URL VARCHAR(255) NOT NULL,
    CONSTRAINT PK_CIRCUIT PRIMARY KEY (CIRCUITID)
);