CREATE SEQUENCE SEQ_RACE;

CREATE TABLE TB_RACE(
    RACEID NUMERIC(20),
    YEAR NUMERIC(10) NOT NULL,
    ROUND NUMERIC(20) NOT NULL,
    CIRCUIT NUMERIC(20) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DATE DATE NOT NULL,
    TIME TIME,
    URL VARCHAR(255) NOT NULL,
    FP1DATE DATE,
    FP1TIME TIME,
    FP2DATE DATE,
    FP2TIME TIME,
    FP3DATE DATE,
    FP3TIME TIME,
    QUALIDATE DATE,
    QUALITIME TIME,
    SPRINTDATE DATE,
    SPRINTTIME TIME,
    CONSTRAINT PK_RACE PRIMARY KEY (RACEID),
    CONSTRAINT FK_RACE_CIRCUIT FOREIGN KEY (CIRCUIT) REFERENCES TB_CIRCUIT (CIRCUITID)
);